# Generated by Django 5.2 on 2025-04-22 16:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=25)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('to', models.CharField(default='', max_length=100)),
                ('from_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=70)),
                ('wa_id', models.CharField(default='', max_length=70)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('step', models.CharField(max_length=64)),
                ('settings', models.JSONField(default=users.models.settings_default_value)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
