# Generated by Django 5.2 on 2025-04-22 16:58

import chatbots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('flow_id', models.CharField(max_length=50, unique=True)),
                ('parent_id', models.CharField(max_length=50, null=True)),
                ('is_options', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('content_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('settings', models.JSONField(default=chatbots.models.settings_default_value)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('question_id', models.CharField(blank=True, max_length=50, null=True)),
                ('question_text', models.TextField(blank=True, null=True)),
                ('selected_option', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('is_bot', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'responses',
            },
        ),
    ]
